CREATE TABLE EMPLOYEE (ID INTEGER, STATUS TEXT, ARR NUMERIC)
PARTITION BY
	HASH (ID);

CREATE TABLE EMP_SMALL PARTITION OF EMPLOYEE FOR
VALUES
WITH
	(MODULUS 3, REMAINDER 0);

CREATE TABLE EMP_MEDIUM PARTITION OF EMPLOYEE FOR
VALUES
WITH
	(MODULUS 3, REMAINDER 1);

CREATE TABLE EMP_LARGE PARTITION OF EMPLOYEE FOR
VALUES
WITH
	(MODULUS 3, REMAINDER 2);

INSERT INTO
	EMPLOYEE
VALUES
	(1, 'ACTIVE', 100),
	(2, 'RECURRING', 20),
	(3, 'EXPIRED', 38),
	(4, 'REACTIVATED', 144);

SELECT
	TABLEOID::REGCLASS,
	*
FROM
	EMPLOYEE;