--LIST PARTITION
CREATE TABLE CUSTOMERS (ID INTEGER, STATUS TEXT, ARR NUMERIC)
PARTITION BY
	LIST (STATUS);

CREATE TABLE CUST_ACTIVE PARTITION OF CUSTOMERS FOR
VALUES
	IN ('ACTIVE');

CREATE TABLE CUST_EXPIRED PARTITION OF CUSTOMERS FOR
VALUES
	IN ('EXPIRED');

CREATE TABLE CUST_OTHERS PARTITION OF CUSTOMERS DEFAULT;

INSERT INTO
	CUSTOMERS
VALUES
	(1, 'ACTIVE', 100),
	(2, 'RECURRING', 20),
	(3, 'EXPIRED', 38),
	(4, 'REACTIVATED', 144);

SELECT
	*
FROM
	CUSTOMERS;

SELECT
	TABLEOID::REGCLASS,
	*
FROM
	CUSTOMERS;