CREATE TABLE DOCTOR (ID INTEGER, STATUS TEXT, ARR NUMERIC)
PARTITION BY
	RANGE (ARR);

CREATE TABLE DOC_SMALL PARTITION OF DOCTOR FOR
VALUES
FROM
	(MINVALUE) TO (25);

CREATE TABLE DOC_MEDIUM PARTITION OF DOCTOR FOR
VALUES
FROM
	(25) TO (75);

CREATE TABLE DOC_LARGE PARTITION OF DOCTOR FOR
VALUES
FROM
	(75) TO (MAXVALUE);

INSERT INTO
	DOCTOR
VALUES
	(1, 'ACTIVE', 100),
	(2, 'RECURRING', 20),
	(3, 'EXPIRED', 38),
	(4, 'REACTIVATED', 144);

SELECT
	TABLEOID::REGCLASS,
	*
FROM
	DOCTOR;

INSERT INTO
	DOCTOR
VALUES
	(5, 'ACTIVE', 25);
